/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAtividadeRouteImport } from './routes/_app/atividade'
import { Route as AppEquipeRouteImport } from './routes/_app/equipe'
import { Route as AppSegurancaRouteImport } from './routes/_app/seguranca'
import { Route as AuthCadastroRouteImport } from './routes/_auth/cadastro'
import { Route as AuthEntrarRouteImport } from './routes/_auth/entrar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadeRoute = AppAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppSegurancaRoute = AppSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AppRoute,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEntrarRoute = AuthEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/convite': typeof ConviteRoute
  '/atividade': typeof AppAtividadeRoute
  '/equipe': typeof AppEquipeRoute
  '/seguranca': typeof AppSegurancaRoute
  '/cadastro': typeof AuthCadastroRoute
  '/entrar': typeof AuthEntrarRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/convite': typeof ConviteRoute
  '/atividade': typeof AppAtividadeRoute
  '/equipe': typeof AppEquipeRoute
  '/seguranca': typeof AppSegurancaRoute
  '/cadastro': typeof AuthCadastroRoute
  '/entrar': typeof AuthEntrarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/convite': typeof ConviteRoute
  '/_app/atividade': typeof AppAtividadeRoute
  '/_app/equipe': typeof AppEquipeRoute
  '/_app/seguranca': typeof AppSegurancaRoute
  '/_auth/cadastro': typeof AuthCadastroRoute
  '/_auth/entrar': typeof AuthEntrarRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convite'
    | '/atividade'
    | '/equipe'
    | '/seguranca'
    | '/cadastro'
    | '/entrar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convite'
    | '/atividade'
    | '/equipe'
    | '/seguranca'
    | '/cadastro'
    | '/entrar'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/convite'
    | '/_app/atividade'
    | '/_app/equipe'
    | '/_app/seguranca'
    | '/_auth/cadastro'
    | '/_auth/entrar'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ConviteRoute: typeof ConviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividade': {
      id: '/_app/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AppAtividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipe': {
      id: '/_app/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguranca': {
      id: '/_app/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof AppSegurancaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/cadastro': {
      id: '/_auth/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/entrar': {
      id: '/_auth/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof AuthEntrarRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AppRouteChildren {
  AppAtividadeRoute: typeof AppAtividadeRoute
  AppEquipeRoute: typeof AppEquipeRoute
  AppSegurancaRoute: typeof AppSegurancaRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtividadeRoute: AppAtividadeRoute,
  AppEquipeRoute: AppEquipeRoute,
  AppSegurancaRoute: AppSegurancaRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthEntrarRoute: typeof AuthEntrarRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCadastroRoute: AuthCadastroRoute,
  AuthEntrarRoute: AuthEntrarRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ConviteRoute: ConviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
